version: '3.7'

services:
  mopidy-client:
    build: .
    image: mopidy-client:latest
    restart: unless-stopped
      #network_mode: host
    volumes:
      - ./mopidy:/var/lib/mopidy
      - snapfifos:/audio
    environment:
      - TZ=America/New_York
  snapserver:
    build: ./shared-snap/
    image: snapserver:latest
    restart: unless-stopped
    depends_on:
      - mopidy-client
    volumes:
      - snapfifos:/audio
    environment:
      - TZ=America/New_York
    ports:
      - "1704:1704"
      - "1780:1780"
volumes:
  snapfifos: 
