version: '2.33'
name: mkrtune
services:
  mopidy:
    build: .
    image: mopidy:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./mopidy:/var/lib/mopidy
      - snapfifos:/audio
    environment:
      - TZ=America/New_York
  snapserver:
    build: ./shared-snap/
    image: snapserver:latest
    restart: unless-stopped
    depends_on:
      - mopidy
    volumes:
      - snapfifos:/audio
    environment:
      - TZ=America/New_York
    ports:
      - "1704:1704"
      - "1780:1780"
volumes:
  snapfifos: 
