version: '3.7'

services:
  mopidy-client:
    build: .
    image: mopidy-client:latest
    restart: always
      #network_mode: host
    volumes:
      - /var/lib/mopidy:/var/lib/mopidy
      - snapfifos:/tmp/sinks
        #environment:
        # - PULSE_SERVER=tcp:127.0.0.1:4713
  snapserver:
    build: ./shared-snap/
    image: snapserver:latest
    restart: always
    depends_on:
      - mopidy-client
    volumes:
      - snapfifos:/tmp/sinks
volumes:
  snapfifos: 
